
#ifndef GUARD_POKEBALL_CONSTANTS_H
#define GUARD_POKEBALL_CONSTANTS_H

enum Ball
{
    BALL_POKE,
    BALL_GREAT,
    BALL_SAFARI,
    BALL_ULTRA,
    BALL_MASTER,
    BALL_NET,
    BALL_DIVE,
    BALL_NEST,
    BALL_REPEAT,
    BALL_TIMER,
    BALL_LUXURY,
    BALL_PREMIER,

    POKEBALL_COUNT
};

#endif // GUARD_POKEBALL_CONSTANTS_H
