#ifndef GUARD_CONSTANTS_TYPE_H
#define GUARD_CONSTANTS_TYPE_H

enum Type
{
    TYPE_NORMAL,
    TYPE_FIGHTING,
    TYPE_FLYING,
    TYPE_POISON,
    TYPE_GROUND,
    TYPE_ROCK,
    TYPE_BUG,
    TYPE_GHOST,
    TYPE_STEEL,
    TYPE_MYSTERY,
    TYPE_FIRE,
    TYPE_WATER,
    TYPE_GRASS,
    TYPE_ELECTRIC,
    TYPE_PSYCHIC,
    TYPE_ICE,
    TYPE_DRAGON,
    TYPE_DARK,

    NUMBER_OF_MON_TYPES,

    TYPE_NONE = 255,
};

enum DamageCategory
{
    DAMAGE_CATEGORY_NONE,
    DAMAGE_CATEGORY_PHYSICAL,
    DAMAGE_CATEGORY_SPECIAL,
};


#endif//GUARD_CONSTANTS_TYPE_H